name: evofill
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
dependencies:
  - python
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda
  - deepspeed
  - cyvcf2
  - pyfaidx
  - tqdm
  - tensorboard
  - pip
  - libstdcxx-ng
  - nccl